postgresql:
  auth:
    username: "keycloak"
    database: "keycloak"
    password: "password123"
    postgresPassword: "password123"

mysql:
  auth:
    rootPassword: "root"
    database: "my_database"
    password: "kJ4PkjxJed"
  service:
    type: NodePort
    nodePorts:
      mysql: 30006

kafka:
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: false
    broker:
      service:
        type: NodePort
        domain: localhost
        ports:
          external: 9094
        nodePorts:
          - 30001
          - 30002
          - 30003

kafka-ui:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    host: "localhost"
    path: "/kafka"
    pathType: "Prefix"

elasticsearch:
  enabled: true
  security:
    elasticPassword: "paassw0rd"

logstash:
  extraEnvVars:
    - name: ELASTICSEARCH_HOST
      value: "resurse-app-elasticsearch"
    - name: ELASTICSEARCH_PORT
      value: "9200"
    - name: ES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: resurse-app-elasticsearch
          key: elasticsearch-password
  service:
    type: NodePort
    ports:
      - name: logstash-tcp
        port: 5044
        targetPort: 5044
        protocol: TCP
        nodePort: 30544

kibana:
  elasticsearch:
    hosts:
      - "resurse-app-elasticsearch"
    security:
      auth:
        kibanaPassword: "paassw0rd"
        elasticsearchPasswordSecret: "resurse-app-elasticsearch"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "localhost"
    path: "/kibana"
    pathType: "Prefix"
    annotations:
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/kibana"

keycloak:
  enabled: true
  httpRelativePath: "/keycloak"
  auth:
    adminUser: "admin"
    adminPassword: "StrongPassword123!"
  externalDatabase:
    host: "postgresql"
    port: 5432
    user: "keycloak"
    password: "password123"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "localhost"
    path: "/keycloak"
    pathType: "Prefix"
    annotations:
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/keycloak"

grafana:
  enabled: true
  admin:
    user: "admin"
    password: "StrongPassword123!"   # local/demo only; rotate for real envs
  ingress:
    enabled: true
    hostname: "localhost"
    path: "/grafana(/|$)(.*)"
    pathType: ImplementationSpecific

# prometheus:
  enabled: true

  alertmanager:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - localhost
      paths:
        - /alertmanager(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
        nginx.ingress.kubernetes.io/use-regex: "true"

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - localhost
      paths:
        - /prometheus(/|$)(.*)
      pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
        nginx.ingress.kubernetes.io/use-regex: "true"